---
- block:
    - name: Save Cisco Conference Endpoint Config
      uri:
        url: "{{ base_url}}/configuration.xml"
        headers:
          Cookie: "SessionId={{ session_id }}"
        method: GET
        return_content: yes
      register: url_output

    - name: Extract XML Config
      set_fact:
        conf_endpoint_config: "{{ url_output.content }}"

    - name: Parse XML Data and place key variables in a JSON structure
      set_fact:
        parsed_conf_endpoint_config: "{{ conf_endpoint_config | parse_xml(spec_file) }}"
  rescue:
    - set_fact:
          failed_to_get_config: true
  when: session_id is defined
