---
- hosts: cisco-endpoints
  connection: local
  gather_facts: no
  vars:
    username: "{{ vault_username }}"
    password: "{{ vault_password }}"
    url_protocol: "{{ vault_url_protocol }}"
    sipdomain_name: " {{ vault_sipdomain_name }}"
    call_control_ips: "{{ vault_call_control_ips }}"
  roles:
    - role: cisco-conference-endpoint-start-session
    - role: cisco-conference-endpoint-config
    - role: cisco-conference-endpoint-h323-to-sip
    - role: cisco-conference-endpoint-close-session

- hosts: all
  connection: local
  gather_facts: no
  roles:
    - role: cisco-conference-endpoint-report
      tags: report
