
- name: Get SIP and H323 Details from the Conference Room Configuration
  set_fact:
    h323_sip_config: "{{ conf_endpoint_config | parse_xml(spec_file) }}"

- name: configure Cisco Conference Endpoint
  uri:
    url: "{{ base_url}}/putxml"
    headers:
      Cookie: "SessionId={{ session_id }}"
    Content-Type: "text/xml"
    method: POST
    body: "{{ lookup('template', 'h323-to-sip.j2') }}"
  changed_when: true
