---
- assert:
    that: parsed_conf_endpoint_config is defined
    msg: >
      conf_endpoint_config should be defined.
      It should contain the XML config of the conference endpoint
- assert:
    that: session_id is defined
    msg: >
      session_id is required to login into the
      Cisco Conference endpoint

- assert:
    that:
      - call_control_ips is defined
      - call_control_ips is iterable
    msg: >
      call_control_ips is list of Call Control Devices (CUCM/VCS)

- assert:
    that: sipdomain_name is defined
    msg: >
      sipdomain_name is required to configure SIP URI

- set_fact:
    sip_endpoint_registered: false


- name: Check if Endpoint is SIP registered
  include_role:
    name: cisco-conference-endpoint-status


- set_fact:
    configure_sip: true

- name: If SIP registration works then no more action ends to be taken.
  block:
    - set_fact:
        configure_sip: false

    - set_fact:
        sip_endpoint_registered: true

    - debug:
        msg: "SIP Endpoint Registered"
  when: endpoint_status_var.sip[0].status == 'Registered'



- name: Proceed with the H323 to SIP conversion
  block:
    - name: convert H323 to SIP
      include_tasks: change-to-sip.yml

    - name:  Verify SIP registration
      include_tasks: verify-sip-config.yml

    - assert:
        that: status_failed is not defined
        msg: "SIP Registration Failed. Switching Back to H323"

    - set_fact:
        sip_configured: true

  rescue:
    - set_fact:
        sip_conversion_failed: true
    - include_tasks: switch-back-to-h323.yml
  when: configure_sip == true
