---
- name: revert config back to H323
  uri:
    url: "{{ base_url}}/putxml"
    headers:
      Cookie: "SessionId={{ session_id }}"
      Content-Type: "text/xml"
    method: POST
    body: "{{ lookup('file', 'convert_back_to_h323.xml') }}"
  changed_when: false
